name: Auto Commit
on:
  workflow_dispatch:
  schedule:
    - cron: '11 0 9 6 *'
    - cron: '50 6 9 6 *'
    - cron: '51 13 9 6 *'
    - cron: '34 18 9 6 *'
    - cron: '4 1 10 6 *'
    - cron: '55 4 10 6 *'
    - cron: '3 6 10 6 *'
    - cron: '33 9 10 6 *'
    - cron: '57 12 10 6 *'
    - cron: '12 16 10 6 *'
    - cron: '55 19 10 6 *'
    - cron: '27 21 10 6 *'
    - cron: '44 0 11 6 *'
    - cron: '22 5 11 6 *'
    - cron: '44 9 11 6 *'
    - cron: '13 12 11 6 *'
    - cron: '7 16 11 6 *'
    - cron: '40 1 12 6 *'
    - cron: '27 3 12 6 *'
    - cron: '17 5 12 6 *'
    - cron: '3 7 12 6 *'
    - cron: '54 8 12 6 *'
    - cron: '0 10 12 6 *'
    - cron: '48 12 12 6 *'
    - cron: '44 14 12 6 *'
    - cron: '32 16 12 6 *'
    - cron: '52 1 13 6 *'
    - cron: '22 4 13 6 *'
    - cron: '28 9 13 6 *'
    - cron: '14 13 13 6 *'
    - cron: '11 17 13 6 *'
    - cron: '54 21 13 6 *'
    - cron: '46 1 14 6 *'
    - cron: '33 2 14 6 *'
    - cron: '45 5 14 6 *'
    - cron: '31 7 14 6 *'
    - cron: '57 8 14 6 *'
    - cron: '13 11 14 6 *'
    - cron: '2 13 14 6 *'
    - cron: '47 14 14 6 *'
    - cron: '45 16 14 6 *'
    - cron: '39 18 14 6 *'
    - cron: '54 0 15 6 *'
    - cron: '24 4 15 6 *'
    - cron: '10 6 15 6 *'
    - cron: '31 10 15 6 *'
    - cron: '16 13 15 6 *'
    - cron: '7 15 15 6 *'
    - cron: '26 18 15 6 *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Set Git Identity
        run: |
          git config --global user.name "Harsh Vekariya"
          git config --global user.email "harshvekariya203@gmail.com"

      - name: Create Single Change
        run: |
          node ./auto_commit_script.js
          git add .
          git commit -m "Auto commit [$(date -u)]"
          git push